site_name: QuantumForce_Code Documentation
# site_url: https://yourdomain.github.io/automotive-docs  # set your public URL
# repo_url: https://github.com/yourusername/QuantumForce_Code # set to your repo
# repo_name: QuantumForce_Code
# edit_uri: edit/main/docs/

site_description: Professional automotive diagnostic tool documentation
site_author: QuantumForce Team

theme:
  name: material
  language: uk
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search:
      lang:
        - en
        - uk
  - mermaid2
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - abbr
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - Tutorials:
    - tutorials/index.md
  - How-To Guides:
    - how-to-guides/index.md
  - Reference:
    - Protocols:
      - OBD-II: reference/protocols/obd-ii.md
      - CAN-UDS: reference/protocols/can-uds.md
      - DoIP: reference/protocols/doip.md
      - J2534: reference/protocols/j2534.md
    - DTC Codes: reference/dtc-codes/index.md
    - API: reference/api/index.md
  - Explanation:
    - explanation/index.md
  - Architecture:
    - Overview: architecture/overview.md
    - Decisions: architecture/decisions/
  - Compliance:
    - EPA: compliance/epa-compliance.md
    - GDPR: compliance/gdpr-compliance.md
    - Legal: compliance/legal-disclaimers.md
    - ISO 26262: compliance/iso-26262.md
  - Development:
    - Monitoring: docs-monitoring.md
    - Quality Metrics: docs-quality-metrics.md
    - Docs Navigator: docs-navigator.md
  - Glossary: glossary.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
  version:
    provider: mike
